name: lournal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  cloud_functions: ^5.5.0
  google_fonts: ^6.2.1
  intl: ^0.18.1
  country_flags: ^3.2.0
  popover: ^0.3.1
  provider: ^6.1.5
  firebase_storage: ^12.4.7
  fake_cloud_firestore: ^3.1.0
  http: ^1.4.0
  firebase_auth_mocks: ^0.14.2
  fake_async: ^1.3.3
  firebase_auth_platform_interface: ^7.7.0
  plugin_platform_interface: ^2.1.8
  # The duplicate entries have been removed from here

dev_dependencies:
  integration_test:
      sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: 2.5.3
  mockito: 5.4.6
  # 1. Add the package to your dev_dependencies
  flutter_launcher_icons: ^0.14.4
  flutter_dotenv: ^5.2.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/lournal-logo-background.png
    - lib/assets/lournal-logo-background-rework.png
    - lib/assets/lournal-logo-background-big.png
    - .env

# 2. Add the configuration block here, at the top level
flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/lournal-logo-background-rework.png"