name: lournal
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Google Services
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.5.0
  google_sign_in: ^7.1.0
  
  # UI & Utilities
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.5
  intl: ^0.18.1
  image_picker: ^1.1.2
  country_flags: ^3.2.0
  popover: ^0.3.1
  http: ^1.4.0
  flutter_native_splash: ^2.4.6
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Core Dev Tools
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11 # Corrected version constraint
  mockito: ^5.4.4 # Corrected version constraint
  flutter_launcher_icons: ^0.13.1 # Corrected version constraint

  # Testing & Mocks
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.2
  fake_async: ^1.3.3
  network_image_mock: ^2.1.1
  
  # Platform Interface Mocks (for testing platform-specific code)
  plugin_platform_interface: ^2.1.8
  image_picker_platform_interface: ^2.10.1
  firebase_auth_platform_interface: ^7.7.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/google.png
    - lib/assets/lournal-logo-big-nobackground.png
    - lib/assets/lournal-logo-background.png
    - lib/assets/lournal-logo-background-big.png
    - lib/assets/lournal-logo-background-rework.png
    
# Launcher Icon Configuration
flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/lournal-logo-background-rework.png"