// Mocks generated by Mockito 5.4.6 from annotations
// in lournal/test/page_tests/edit_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:lournal/services/firestore.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCollectionReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i3.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
      ) as String);

  @override
  _i2.CollectionReference<Object?> get userNotesCollection =>
      (super.noSuchMethod(
        Invocation.getter(#userNotesCollection),
        returnValue: _FakeCollectionReference_0<Object?>(
          this,
          Invocation.getter(#userNotesCollection),
        ),
      ) as _i2.CollectionReference<Object?>);

  @override
  _i5.Future<void> addNote({
    required String? title,
    required String? content,
    required String? language,
    required String? type,
    required String? translation,
    required String? feedback,
    required int? score,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNote,
          [],
          {
            #title: title,
            #content: content,
            #language: language,
            #type: type,
            #translation: translation,
            #feedback: feedback,
            #score: score,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<_i2.QuerySnapshot<Object?>> getNotesStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotesStream,
          [],
        ),
        returnValue: _i5.Stream<_i2.QuerySnapshot<Object?>>.empty(),
      ) as _i5.Stream<_i2.QuerySnapshot<Object?>>);

  @override
  _i5.Future<void> updateNote({
    required String? docID,
    required String? title,
    required String? content,
    required String? language,
    required String? type,
    required String? translation,
    required String? feedback,
    required int? score,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [],
          {
            #docID: docID,
            #title: title,
            #content: content,
            #language: language,
            #type: type,
            #translation: translation,
            #feedback: feedback,
            #score: score,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteNote(String? docID) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [docID],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUserAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserAccount,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
